config/routes.rb
Rails.application.routes.draw do
  resources :element_properties
  resources :elements
  resources :pages do
    resources :page_elements
  end

  root 'static_pages#home'
end

app/models/element_property.rb
class ElementProperty < ApplicationRecord
  belongs_to :element
end

app/controllers/element_properties_controller.rb
class ElementPropertiesController < ApplicationController
  before_action :set_element_property, only: %i[ show edit update destroy ]

  # GET /element_properties or /element_properties.json
  def index
    @element_properties = ElementProperty.all
  end

  # GET /element_properties/1 or /element_properties/1.json
  def show
  end

  # GET /element_properties/new
  def new
    @element_property = ElementProperty.new
  end

  # GET /element_properties/1/edit
  def edit
  end

  # POST /element_properties or /element_properties.json
  def create
    @element_property = ElementProperty.new(element_property_params)

    respond_to do |format|
      if @element_property.save
        format.html { redirect_to element_property_url(@element_property), notice: "Element property was successfully created." }
        format.json { render :show, status: :created, location: @element_property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @element_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /element_properties/1 or /element_properties/1.json
  def update
    respond_to do |format|
      if @element_property.update(element_property_params)
        format.html { redirect_to element_property_url(@element_property), notice: "Element property was successfully updated." }
        format.json { render :show, status: :ok, location: @element_property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @element_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /element_properties/1 or /element_properties/1.json
  def destroy
    @element_property.destroy

    respond_to do |format|
      format.html { redirect_to element_properties_url, notice: "Element property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element_property
      @element_property = ElementProperty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_property_params
      params.require(:element_property).permit(:element_id, :name, :input_type, :value)
    end
end

app/views/element_properties/_form.html.erb
<%= form_with(model: element_property) do |form| %>
  <% if element_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(element_property.errors.count, "error") %> prohibited this element_property from being saved:</h2>

      <ul>
        <% element_property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :element_id %>
    <%= form.text_field :element_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/element_properties/edit.html.erb
<h1>Editing Element Property</h1>

<%= render 'form', element_property: @element_property %>

<%= link_to 'Show', @element_property %> |
<%= link_to 'Back', element_properties_path %>

app/views/element_properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Element Properties</h1>

<table>
  <thead>
    <tr>
      <th>Element</th>
      <th>Name</th>
      <th>Type</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @element_properties.each do |element_property| %>
      <tr>
        <td><%= element_property.element_id %></td>
        <td><%= element_property.name %></td>
        <td><%= element_property.type %></td>
        <td><%= element_property.value %></td>
        <td><%= link_to 'Show', element_property %></td>
        <td><%= link_to 'Edit', edit_element_property_path(element_property) %></td>
        <td><%= link_to 'Destroy', element_property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Element Property', new_element_property_path %>

app/views/element_properties/new.html.erb
<h1>New Element Property</h1>

<%= render 'form', element_property: @element_property %>

<%= link_to 'Back', element_properties_path %>

app/views/element_properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Element:</strong>
  <%= @element_property.element_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @element_property.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @element_property.type %>
</p>

<p>
  <strong>Value:</strong>
  <%= @element_property.value %>
</p>

<%= link_to 'Edit', edit_element_property_path(@element_property) %> |
<%= link_to 'Back', element_properties_path %>