config/routes.rb
Rails.application.routes.draw do
  resources :element_properties
  resources :elements
  resources :pages do
    resources :page_elements
  end

  root 'static_pages#home'
end

app/models/element.rb
class Element < ApplicationRecord
  has_many :element_properties, inverse_of: :element
  has_many :page_elements, dependent: :nullify

  accepts_nested_attributes_for :element_properties, allow_destroy: true, reject_if: :all_blank

end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: %i[ show edit update destroy ]

  # GET /elements or /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1 or /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements or /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to element_url(@element), notice: "Element was successfully created." }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1 or /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to element_url(@element), notice: "Element was successfully updated." }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1 or /elements/1.json
  def destroy
    @element.destroy

    respond_to do |format|
      format.html { redirect_to elements_url, notice: "Element was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:name, :element_type, element_properties_attributes: [:id, :name, :input_type, :value, :_destroy])
    end
end

app/views/elements/_element_property_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :_destroy %>
  <div class="field">
    <%= f.label :name, class: 'label' %>
    <div class="control">
        <%= f.text_field :name, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :input_type, class: 'label' %>
    <div class="control">
      <%= f.text_field :input_type, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :value, class: 'label' %>
    <div class="control">
      <%= f.text_field :value, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
  </div>
</div>

app/views/elements/_form.html.erb
<%= form_with(model: element) do |form| %>
  <% if element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
        <% element.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: 'label' %>
    <div class="control">
      <%= form.text_field :name, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :element_type, class: 'label' %>
    <div class="control">
      <%= form.text_field :element_type, class: 'input' %>
    </div>
  </div>

  <hr />

  <fieldset>
    <h4 class="title is-4">Properties:</h4>
    <%= form.fields_for :element_properties  do |property| %>
      <%= render "element_property_fields", f: property %>
    <% end %>
    <%= link_to_add_fields "Add Property", form, :element_properties %>
  </fieldset>
  
  <hr />

  <div class="field">
    <div class="control">
      <%= form.submit 'Save', class: 'button is-link' %>
    </div>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1 class="title">Editing Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Elements</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Element Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.name %></td>
        <td><%= element.element_type%></td>
        <td><%= link_to 'Show', element %></td>
        <td><%= link_to 'Edit', edit_element_path(element) %></td>
        <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Element', new_element_path, class: 'button is-info' %>

app/views/elements/new.html.erb
<h1 class="title">New Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @element.name %>
</p>
<p>
  <strong>Element Type:</strong>
  <%= @element.element_type %>
</p>

<div>
  <strong>Properties:</strong>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Input Type</th>
      <th>Value</th>
    </tr>
  </thead>

  <tbody>
    <% @element.element_properties.each do |prop|%>
      <tr>
        <td><%= prop.name %></td>
        <td><%= prop.input_type%></td>
        <td><%= prop.value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Edit', edit_element_path(@element) %> |
  <%= link_to 'Back', elements_path %>
</div>