config/routes.rb
Rails.application.routes.draw do
  resources :element_properties
  resources :elements
  resources :pages do
    resources :page_elements
  end

  root 'static_pages#home'
end

app/models/page_element.rb
class PageElement < ApplicationRecord
  belongs_to :page
  belongs_to :element

  serialize :properties

end

app/controllers/page_elements_controller.rb
class PageElementsController < ApplicationController
  before_action :set_page
  before_action :set_element, only: %i[ new create edit update ]
  before_action :set_page_element, only: %i[ show edit update destroy ]

  # GET /page_elements or /page_elements.json
  def index
    @page_elements = PageElement.all
  end

  # GET /page_elements/1 or /page_elements/1.json
  def show
  end

  # GET /page_elements/new
  def new
    @page_element = @page.page_elements.new
    set_default_values
  end

  # GET /page_elements/1/edit
  def edit
  end

  # POST /page_elements or /page_elements.json
  def create
    @page_element = @page.page_elements.new(page_element_params)
    @page_element.element_id = @element.id

    respond_to do |format|
      if @page_element.save
        format.html { redirect_to edit_page_path(@page), notice: "Page element was successfully created." }
        format.json { render :show, status: :created, location: @page_element }
      else
        format.html { redirect_to edit_page_path(@page), status: :unprocessable_entity }
        format.json { render json: @page_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_elements/1 or /page_elements/1.json
  def update
    respond_to do |format|
      if @page_element.update(page_element_params)
        format.html { redirect_to edit_page_path(@page), notice: "Page element was successfully updated." }
        format.json { render :show, status: :ok, location: @page_element }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_elements/1 or /page_elements/1.json
  def destroy
    @page_element.destroy

    respond_to do |format|
      format.html { redirect_to edit_page_path(@page), notice: "Page element was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:page_id])
    end

    def set_element
      @element = Element.find_by(element_type: params[:element_type])
    end

    def set_page_element
      @page_element = PageElement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_element_params
      # params.require(:page_element).permit(:element_id, properties: {})
      params.require(:page_element).permit(:element_id, properties: set_properties)
    end

    def set_properties
      @element.element_properties.map do |property|
        property[:name].to_sym
      end
    end

    def set_default_values
      @page_element.properties = {}
      @element.element_properties.each do |property|
        @page_element.properties[property[:name]] = property[:value]
      end
    end
end

app/views/page_elements/_form.html.erb
<%= form_with(model: page_element) do |form| %>
  <% if page_element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page_element.errors.count, "error") %> prohibited this page_element from being saved:</h2>

      <ul>
        <% page_element.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :page_id %>
    <%= form.text_field :page_id %>
  </div>

  <div class="field">
    <%= form.label :element_id %>
    <%= form.text_field :element_id %>
  </div>

  <div class="field">
    <%= form.label :properties %>
    <%= form.text_field :properties %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/page_elements/edit.html.erb
<h1>Editing Page Element</h1>

<%= render 'form', page_element: @page_element %>

<%= link_to 'Show', @page_element %> |
<%= link_to 'Back', page_elements_path %>

app/views/page_elements/edit.js.erb
document.querySelector("#element-properties-form").innerHTML = ("<%= j render "page_elements/elements/#{@element.element_type}_form", page: @page, page_element: @page_element %>")

app/views/page_elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Page Elements</h1>

<table>
  <thead>
    <tr>
      <th>Page</th>
      <th>Element</th>
      <th>Properties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @page_elements.each do |page_element| %>
      <tr>
        <td><%= page_element.page_id %></td>
        <td><%= page_element.element_id %></td>
        <td><%= page_element.properties %></td>
        <td><%= link_to 'Show', page_element %></td>
        <td><%= link_to 'Edit', edit_page_element_path(page_element) %></td>
        <td><%= link_to 'Destroy', page_element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page Element', new_page_element_path %>

app/views/page_elements/new.js.erb
document.querySelector("#page-element-content").insertAdjacentHTML("beforeend", "<%= j render "page_elements/elements/#{@element.element_type}_edit", page_element: @page_element %>")

document.querySelector("#element-properties-form").innerHTML = ("<%= j render "page_elements/elements/#{@element.element_type}_form", page: @page, page_element: @page_element %>")

app/views/page_elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @page_element.page_id %>
</p>

<p>
  <strong>Element:</strong>
  <%= @page_element.element_id %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @page_element.properties %>
</p>

<%= link_to 'Edit', edit_page_element_path(@page_element) %> |
<%= link_to 'Back', page_elements_path %>