config/routes.rb
Rails.application.routes.draw do
  resources :element_properties
  resources :elements
  resources :pages do
    resources :page_elements
  end

  root 'static_pages#home'
end

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: 'label' %>
    <div class="control">
      <%= form.text_field :name, class: 'input' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'button is-link' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="columns">
  <div class="column is-three-quarters">
  
    <h2 class="title is-2">Editing Page</h2>

    <div class="columns is-half">
      <%= render 'form', page: @page %>
    </div>

    <%= link_to 'Show', @page %> |
    <%= link_to 'Back', pages_path %>
    <hr />
    <div id="page-element-content">
      <% @page.page_elements.each do |el| %>
        <%= render "page_elements/elements/#{el.element.element_type}_edit", page_element: el %>
      <% end %>
    </div>
  </div>

  <div class="column">
    <h3 class="title is-4 mb-2">Elements</h3>

    <% @elements.each do |el| %>
        <%= link_to el.name, new_page_page_element_path(@page, element_type: el.element_type), remote: true, role: "button", class: "button is-fullwidth is-info mb-2" %>
    <% end %>
    <hr />
    <div id="element-properties-form"></div>
  </div>
</div>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Pages</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.name %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path, class: 'button is-info' %>

app/views/pages/new.html.erb
<h1 class="title is-2">New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title is-2">
  <%= @page.name %>
</h1>
<hr />
<div id="page-element-content">
  <% @page.page_elements.each do |el| %>
    <%= render "page_elements/elements/#{el.element.element_type}", page_element: el %>
  <% end %>

<hr />
<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>